config/routes.rb
Rails.application.routes.draw do
  # 登入用：
  resources :sessions do
    collection do
      post :wechat_login
      post :admin_required
    end
  end

  root "welcome#home"
  resources :users
  delete '/logout' => 'sessions#destroy', as: :logout

  get "welcome" => "welcome#index"

  get '/admin/recent_login_log' => "admin/recent_login_log"
  get '/admin/get_user_login_log' => "admin/get_user_login_log"
  post "/kexue/update_ss_item" => "kexue/update_ss_item"
  get 'kexue/get_qr' => "kexue/get_qr"
  get 'kexue/show_qr' => "kexue/show_qr"
  get "kexue/show_wingy_qr" => "kexue/show_wingy_qr"
  get "server_data" => 'application#server_data'

  resources :categories do
    collection do
      get :for_wechat_product_new_picker
      get :for_wechat_category_new_picker
      post :create_form_api
    end
    member do
      post :update_column
      post :update_form_api
      get :get_category_detail
      post :change_index_show_status
      post :delete_category
    end
  end
  resources :products do
    collection do
      post :create_form_wechat
    end
    member do
      post :update_form_wechat
      post :add_product_image
      get :get_product_detail
      post :change_is_hide_status
      post :change_in_stock_status
      post :change_index_show_status
      post :delete_form_wechat
    end
  end
  resources :homeset do
    member do
      post :update_column
      post :update_column_homeset
      post :change_is_hide_status
    end
    collection do
      # 获取小程序首页的图片，标题等配置
      get :get_wechat_homeset
    end
  end
  resources :collects do
    collection do
      post :create_collect
      delete :remove_clooect
      get :my_collects
    end
  end


  resources :ss_services do
    resources :ss_items do
      member do
        get :admin_show_qr
        post :change_send_status
        post :init_draw_time
      end
    end
  end


end

app/models/category.rb
class Category < ApplicationRecord
  mount_uploader :image, CategoryImageUploader
  mount_uploader :index_image, HomepageCategoryImageUploader

  validates_presence_of :title, message: "标题不能为空！"
  has_ancestry
  has_many :products, dependent: :destroy

  scope :ascend, -> { order(weight: "asc") }

  # 返回分类树
  def self.render_category_tree
    category_roots = self.includes(:products).roots.ascend
    scroll_a = []
    item_a = []
    tmp = 0
    sum = Hash.new(0)
    category_roots.map{|x| scroll_a <<  ((x.children.count + x.products.count) / 3.000).ceil }
    category_roots.map{|x| item_a << ((x.children.count + x.products.count) / 3.000).ceil * 126 + 88 }
    category_roots.map{|x| sum["item"] += ((x.children.count + x.products.count) / 3.000).ceil; sum["title"] += 1}
    return {sum: sum, item_a: item_a, scroll_detail: scroll_a, test: "test", tree:  category_roots.map{|r| { id: r.id, title: r.title, products: render_products(r), children: render_children(r) }}}
  end

  def update_form_website(params)
    self.image = params[:category][:image] if params[:category][:image].present?
    self.weight = params[:category][:weight] if params[:category][:weight].present?
    self.title = params[:category][:title] if params[:category][:title].present?
    self.index_show = params[:category][:index_show] if params[:category][:index_show].present?
    self.index_image = params[:category][:index_image] if params[:category][:index_image].present?
    self.index_weight = params[:category][:index_weight] if params[:category][:index_weight].present?
    return self.save ? "已更新！" : "操作失败，请联系管理员"
  end

  def update_form_api(params)
    self.title = params[:title] if params[:title].present?
    self.weight = params[:weight] if params[:weight].present?
    self.image = params[:image] if params[:image].present?
    self.ancestry = params[:parent_id] if params[:parent_id].present?
    return self.save ? { status: "ok", id: self.id } : { status: "failed", info: self.errors.messages.values.flatten }
  end

  def change_index_show_status!
    self.index_show = !self.index_show
    self.save
  end

  private

  def self.render_products(root)
    return root.products.map{|p| { id: p.id, title: p.title[0..4] + "...", image: (p.product_images.present? ? p.product_images.shuffle.last.image.thumb.url : "")}}
  end

  def self.render_children(root)
    if root.children.present?
      return root.children.order(weight: 'asc').map{|c| { id: c.id, title: c.title, image: c.image.thumb.url }}
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :auth_admin_or_wechat_user
  # before_action :admin_required_site_or_wechat
  protect_from_forgery except: [:create_form_api, :update_form_api, :update_image_form_api]
  before_action :find_category, only: [:show, :update_column, :destroy, :change_index_show_status, :delete_category, :update_form_api, :get_category_detail]

  def index
    @category_roots = Category.includes(:products).roots.ascend
    @category = Category.new
    respond_to do |format|
      format.html{
        @index_show_category = Category.where(index_show: true).order(index_weight: 'asc')
      }
      format.json{
        # 返回小程序端的分类树
        render json: Category.render_category_tree
      }
    end
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path, notice: "新增成功！"
    else
      render :back
    end
  end

  def show
    new_products = Product.where( "created_at >= ?", (Date.today - 30).beginning_of_day ) if params[:id] == "新品"
    respond_to do |format|
      format.html
      format.json{
        # 返回小程序端分类下产品列表
        render :json => ( new_products || @category.products ).includes(:product_images).map{|p| {id: p.id, title: p.title, sub_title: p.sub_title, price: p.price, image: p.main_image_thumb}}
      }
    end
  end

  def destroy
    if @category.destroy
      redirect_to categories_path, alert: "已删除"
    else
      redirect_to :back, alert: "操作失败，请联系程序员"
    end
  end

  # 页面版的更新栏位数据
  def update_column
    redirect_to :back, notice: @category.update_form_website(params)
  end

  # wechat端需要新增分类时，获取的分类列表
  def for_wechat_product_new_picker
    roots = Category.where(ancestry: nil)
    render :json => {title_arr: roots.map{|r| [r.title, ["- -"] + r.children.map{|c| c.title}]}, id_arr: roots.map{|r| [r.id, [00] + r.children.map{|c| c.id}]}, default_arr: [ roots.map{|r| r.title}, ["- -"] + roots.first.children.map{|c| c.title}], current_id: roots.first.id, current_title: roots.first.title}
  end

  # 为小程序端获取一级分类
  def for_wechat_category_new_picker
    roots = Category.where(ancestry: nil)
    render :json => {title_arr: ["(新增一级分类)"] + roots.map{|r| r.title}, id_arr: ["00"] + roots.map{|r| r.id}}
  end


  # 新增来自wechat端
  def create_form_api
    category = Category.new title: params[:title], weight: params[:weight], ancestry: ( params[:parent_id] if params[:parent_id].present? )
    if category.save
      render :json => { status: "ok", id: category.id }
    else
      render :json => { status: "failed", info: category.errors.messages.values.flatten }
    end
  end

  # 由wechat端发起更新
  def update_form_api
    render json: @category.update_form_api(params)
  end


  # 获取一条数据的详情，用于编辑
  def get_category_detail
    if @category.present?
      render :json => { id: @category.id, title: @category.title, weight: @category.weight, image: (@category.image.url if @category.image.present?)}
    end
  end

  # 更改index_show的状态
  def change_index_show_status
    @category.change_index_show_status!
    redirect_to :back, notice: "更新成功~"
  end

  # 由小程序端更改category状态
  def delete_category
    title = @category.title
    if @category.destroy
      render :json => {status: "ok", info: "【#{title}】已删除！"}
    else
      render :json => {status: "failed", info: "删除失败，请联系程序员..."}
    end
  end


  # 私有方法
  private
  def category_params
    params.require(:category).permit(:title, :weight, :ancestry, :image)
  end

  def find_category
    @category = Category.find(params[:id])
  end

  def find_root
    returnroots = Category.where(ancestry: nil)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<legend class="text-center">分类管理<i class="fa fa-cogs" aria-hidden="true"></i></legend>

<div class="row">
  <div class="container-fluid">
  <!-- bootstrap标签风格 -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active test-btn"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">所有分类汇总</a></li>
    <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">在小程序首页推广的分类</a></li>
  </ul>

<!-- 第一个卡片 -->
<div class="tab-content">
  <div role="tabpanel" class="tab-pane fade in active" id="home">
    <% @category_roots.each do |root| %>
      <div class="row well well-sm well-success">
        <div class="col-sm-5">
          <%= form_for root, url: update_column_category_path(root), method: :post do |f| %>
            <%= f.text_field :title, :value => root.title %>
            <%= f.submit "更名", class: "btn btn-xs btn-default" %>
          <% end %>
        </div>
        <div class="col-sm-5">
          <%= form_for root, url: update_column_category_path(root), method: :post do |f| %>
          <%= f.text_field :weight %>
          <%= f.submit "更新", class: "btn btn-xs btn-default" %>
          <% end %>
        </div>
        <div class="col-sm-2">
          <%= link_to "删除", category_path(root), method: :delete, "data-confirm": "分类下的所有东西会一起删除，确定吗？", class: "btn btn-xs btn-danger" %>
        </div>
      </div>
      <table class="table table-bordered table-condensed">
        <% root.children.each do |c| %>
          <tr>
            <td>
              ID:
              <%= c.id %>
            </td>
            <td>
              <%= form_for c, url: update_column_category_path(c), method: :post do |f| %>
                <%= f.text_field :title, :value => c.title %>
                <%= f.submit "更名", class: "btn btn-xs btn-default" %>
              <% end %>
            </td>
            <td>
              <div class="row">
                <div class="col-sm-12">
                  <%= form_for c, url: update_column_category_path(c), method: :post do |f| %>
                  <%= f.file_field :image %>
                  <%= f.submit "更新", class: "btn btn-xs btn-success btn-block" %>
                  <% end %>
                </div>
                <div class="col-sm-12">
                  <% if c.image.present? %>
                    <%= image_tag(c.image.thumb.url, class: "img-responsive thumbnail", width: '70') %>
                  <% else %>
                    <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "pull-right img-responsive thumbnail", width: '70') %>
                  <% end %>
                </div>
              </div>
            </td>
            <td>
              <%= form_for c, url: update_column_category_path(c), method: :post do |f| %>
              <%= f.text_field :weight %>
              <%= f.submit "更新", class: "btn btn-xs btn-default" %>
              <% end %>
            </td>
            <td>
              <%= render_hide_status(c.index_show == false) %>
              <%= link_to "更改状态", change_index_show_status_category_path(c), method: :post, class: "btn btn-xs btn-danger" %>
            </td>
            <td>
              <%= link_to "商品", category_path(c), class: "btn btn-success btn-xs" %>
              <%= link_to "删除", category_path(c), method: :delete, "data-confirm": "分类下的所有东西将会一起被清除，确认继续吗？", class: "btn btn-xs btn-primary" %>
            </td>
          </tr>
        <% end %>
      </table>
    <% end %>

    <div class="row">
      <div class="col-sm-6">
        <legend>增加一级分类</legend>
        <%= simple_form_for @category do |f| %>
        <%= f.input :title %>
        <%= f.input :weight %>
        <%= f.input :image %>
        <%= f.submit "提交", class: "btn btn-primary btn-block" %>
        <% end %>
      </div>
      <div class="col-sm-6">
        <legend>增加二级分类</legend>
        <%= simple_form_for @category do |f| %>

        <select name="category[ancestry]">
          <% @category_roots.each do |category| %>
            <option value="<%= category.id %>"><%= category.title %></option>
          <% end %>
        </select>

        <%= f.input :title %>
        <%= f.input :weight %>
        <%= f.input :image %>
        <%= f.submit "提交", class: "btn btn-primary btn-block" %>
        <% end %>
      </div>
    </div>

  </div>


  <!-- 第二个卡片 -->
  <div role="tabpanel" class="tab-pane fade" id="profile">
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>ID</th>
        <th>标题</th>
        <th>图片</th>
        <th>在首页要展示的图标</th>
        <th>更改首页图标</th>
        <th>在首页展示的排序</th>
        <th>操作</th>
      </tr>
    </thead>
    <tbody>
      <% @index_show_category.each do |c| %>
        <tr>
          <td><%= c.id %></td>
          <td><%= c.title %></td>
          <td>
            <% if c.image.present? %>
            <%= image_tag c.image.thumb.url, class: "thumbnail img-responsive" %>
            <% end %>
          </td>
          <td width=130>
            <% if c.index_image.present? %>
            <%= image_tag c.index_image.url, class: "thumbnail img-responsive"  %>
            <% end %>
          </td>
          <td>
            <%= form_for c, url: update_column_category_path(c), method: :post do |f| %>
            <%= f.file_field :index_image %>
            <%= f.submit "更改首页展示图标", class: "btn btn-xs btn-success" %>
            <% end %>
          </td>
          <td>
            <%= form_for c, url: update_column_category_path(c), method: :post do |f| %>
            <%= f.text_field :index_weight, value: c.index_weight %>
            <%= f.submit "更新", class: "btn btn-xs btn-default" %>
            <% end %>
          </td>
          <td><%= link_to "删除", category_path(c), method: :delete, class: "btn btn-xs btn-danger", "data-confirm": "确定删除？" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

</div>
</div>
</div>



<script>
// bootstrap的卡片辅助js


$('#myTabs a[href="#profile"]').tab('show') // Select tab by name
$('#myTabs a:first').tab('show') // Select first tab
$('#myTabs a:last').tab('show') // Select last tab
$('#myTabs li:eq(2) a').tab('show') // Select third tab (0-indexed)
$('#myTabs a').click(function (e) {e.preventDefault()
$(this).tab('show')
})

</script>

app/views/categories/show.html.erb
<legend>当前分类：【<%= @category.title %>】下的商品列表</legend>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>ID</th>
      <th>名称</th>
      <th>副标题</th>
      <th>price</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
    <% @category.products.each do |p| %>
    <tr>
      <td><%= p.id %></td>
      <td><%= link_to p.title, product_path(p)%></td>
      <td><%= p.sub_title %></td>
      <td><%= p.price %></td>
      <td><%= link_to "删除", product_path(p), class: "btn btn-sm btn-danger", method: :delete, "data-confirm": "您确定吗？" %></td>
    </tr>
    <% end %>
  </tbody>
</table>