config/routes.rb
Rails.application.routes.draw do
  # 登入用：
  resources :sessions do
    collection do
      post :wechat_login
      post :admin_required
    end
  end

  root "welcome#home"
  resources :users
  delete '/logout' => 'sessions#destroy', as: :logout

  get "welcome" => "welcome#index"

  get '/admin/recent_login_log' => "admin/recent_login_log"
  get '/admin/get_user_login_log' => "admin/get_user_login_log"
  post "/kexue/update_ss_item" => "kexue/update_ss_item"
  get 'kexue/get_qr' => "kexue/get_qr"
  get 'kexue/show_qr' => "kexue/show_qr"
  get "kexue/show_wingy_qr" => "kexue/show_wingy_qr"
  get "server_data" => 'application#server_data'

  resources :categories do
    collection do
      get :for_wechat_product_new_picker
      get :for_wechat_category_new_picker
      post :create_form_api
    end
    member do
      post :update_column
      post :update_form_api
      get :get_category_detail
      post :change_index_show_status
      post :delete_category
    end
  end
  resources :products do
    collection do
      post :create_form_wechat
    end
    member do
      post :update_form_wechat
      post :add_product_image
      get :get_product_detail
      post :change_is_hide_status
      post :change_in_stock_status
      post :change_index_show_status
      post :delete_form_wechat
    end
  end
  resources :homeset do
    member do
      post :update_column
      post :update_column_homeset
      post :change_is_hide_status
    end
    collection do
      # 获取小程序首页的图片，标题等配置
      get :get_wechat_homeset
    end
  end
  resources :collects do
    collection do
      post :create_collect
      delete :remove_clooect
      get :my_collects
    end
  end


  resources :ss_services do
    resources :ss_items do
      member do
        get :admin_show_qr
        post :change_send_status
        post :init_draw_time
      end
    end
  end


end

app/models/ss_item.rb
class SsItem < ApplicationRecord

  belongs_to :service, class_name: SsService
  enum status: [:init , :complete]


  def expired?
    if self.draw_date.present? && self.draw_date < Time.now - 600
      true
    else
      false
    end
  end

  def android_code
    qr_code = "ss://" + (Base64.strict_encode64("rc4-md5:#{self.password}")).to_s + "@" + self.domain + ":" + self.port.to_s + "/?OTA=false"
  end

  def shadow_qr_code
    qr_code = "ss://" + (Base64.strict_encode64("rc4-md5:#{self.password}")).to_s + "@" + self.domain + ":" + self.port.to_s + "/?OTA=false"
    qr_code = (qr_code + '#' + URI.encode(self.wechat)) if self.wechat.present?
    qr_code = RQRCode::QRCode.new(qr_code.to_s, :size => 9, :level => :m)
  end

  def wingy_qr_code
    qr_code = "ss://" + (Base64.strict_encode64("rc4-md5:#{self.password}@#{self.domain}:#{self.port}")).to_s + "?rule=general"
    qr_code = (qr_code + '#' + URI.encode(self.wechat)) if self.wechat.present?
    qr_code = RQRCode::QRCode.new(qr_code.to_s, :size => 9, :level => :m)
  end
end

app/controllers/ss_items_controller.rb
class SsItemsController < ApplicationController
  before_action :auth_admin_or_wechat_user


  def index
    @ss_items = SsItem.where(ss_service_id: params[:ss_service_id]).order("is_send asc")
  end

  def change_send_status
    @ss_item= SsItem.find(params[:id])
    if @ss_item.is_send
      @ss_item.update is_send: false
    else
      @ss_item.update is_send: true
    end
    redirect_to ss_service_ss_items_path(@ss_item.ss_service_id), notice: "更改成功~"
  end

  def init_draw_time
    @ss_item = SsItem.find(params[:id])
    @ss_item.update draw_date: nil
    redirect_to ss_service_ss_items_path(@ss_item.ss_service_id), notice: "更改成功~"
  end

  def admin_show_qr
    @ss_item = SsItem.find(params[:id])
    @qr = @ss_item.shadow_qr_code
  end
end

app/helpers/ss_items_helper.rb
module SsItemsHelper
end

app/views/ss_items/admin_show_qr.html.erb
<div class="container">
  <div class="col-sm-4 col-sm-offset-4">
    <br>
    <br>
    <div class="qr-code text-center" id="ss_qrcode">
      <%= raw @qr.as_html %>
    </div>
  </div>
</div>

app/views/ss_items/index.html.erb
<%= link_to "返回服务器页面", ss_services_path, class: "btn btn-sm btn-primary" %>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>端口</th>
      <th>password</th>
      <th>qr_code</th>
      <th>wechat</th>
      <th>是否已领取</th>
      <th>是否已送出</th>
      <th>送出链接</th>
      <th>重生效10分钟</th>
      <th>draw_date</th>
      <th>re_code</th>
      <th>状态</th>
      <th>wingy的领取链接</th>
    </tr>
  </thead>
  <tbody>
    <% @ss_items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= item.port %></td>
        <td><%= item.password %></td>
        <td>
          <div style="word-break:break-all; width: 220px;">
            <%= item.android_code %>
          </div>
          <%= link_to "查看二维码", admin_show_qr_ss_service_ss_item_path(item.ss_service_id, item.id), class: "btn btn-sm btn-success" %>
        </td>
        <td><%= item.wechat %></td>
        <td><%= render_status_display item.is_draw %></td>
        <td>
          <%= render_status_display item.is_send %>
          <% unless item.is_send %>
            <%= link_to "标记为送出", change_send_status_ss_service_ss_item_path(item.ss_service_id, item.id), method: :post, class: "btn btn-sm btn-success" %>
          <% end %>
        </td>
        <td width="300">
          <div style="min-width: 300px;" class="form-group">
              <%= text_area_tag nil,  "#{root_url}/kexue/get_qr?re_code=#{item.re_code}",  class: "form-control" %>
          </div>
        </td>
        <td><%= link_to "链接重生效", init_draw_time_ss_service_ss_item_path(item.ss_service_id, item.id), method: :post, class: "btn btn-danger btn-sm" %></td>
        <td>
          <% if item.draw_date.present? %>
          <%= item.draw_date.strftime("%y-%m-%d %H:%M") %>
          <% end %>
        </td>
        <td>
          <div style="word-break:break-all; width: 220px;">
            <%= item.re_code %>
          </div>
        </td>
        <td><%= item.status %></td>
        <td>
          <div style="min-width: 300px;" class="form-group">
              <%= text_area_tag nil,  "#{root_url}/kexue/show_wingy_qr?re_code=#{item.re_code}",  class: "form-control" %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>