config/routes.rb
Rails.application.routes.draw do
  # 登入用：
  resources :sessions do
    collection do
      post :wechat_login
      post :admin_required
    end
  end

  root "welcome#home"
  resources :users
  delete '/logout' => 'sessions#destroy', as: :logout

  get "welcome" => "welcome#index"

  get '/admin/recent_login_log' => "admin/recent_login_log"
  get '/admin/get_user_login_log' => "admin/get_user_login_log"
  post "/kexue/update_ss_item" => "kexue/update_ss_item"
  get 'kexue/get_qr' => "kexue/get_qr"
  get 'kexue/show_qr' => "kexue/show_qr"
  get "kexue/show_wingy_qr" => "kexue/show_wingy_qr"
  get "server_data" => 'application#server_data'

  resources :categories do
    collection do
      get :for_wechat_product_new_picker
      get :for_wechat_category_new_picker
      post :create_form_api
    end
    member do
      post :update_column
      post :update_form_api
      get :get_category_detail
      post :change_index_show_status
      post :delete_category
    end
  end
  resources :products do
    collection do
      post :create_form_wechat
    end
    member do
      post :update_form_wechat
      post :add_product_image
      get :get_product_detail
      post :change_is_hide_status
      post :change_in_stock_status
      post :change_index_show_status
      post :delete_form_wechat
    end
  end
  resources :homeset do
    member do
      post :update_column
      post :update_column_homeset
      post :change_is_hide_status
    end
    collection do
      # 获取小程序首页的图片，标题等配置
      get :get_wechat_homeset
    end
  end
  resources :collects do
    collection do
      post :create_collect
      delete :remove_clooect
      get :my_collects
    end
  end


  resources :ss_services do
    resources :ss_items do
      member do
        get :admin_show_qr
        post :change_send_status
        post :init_draw_time
      end
    end
  end


end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :video, ProductVideoUploader
  serialize :images, JSON

  validates_presence_of :category_id, message: "所属分类不能为空"
  validates_presence_of :title, message: "商品名称不能为空"
  validates_presence_of :sub_title, message: "副标题不能为空"
  validates_presence_of :price, message: "价格不能为空"
  validates_presence_of :description, message: "商品详情不能为空"


  belongs_to :category
  has_many :product_images, -> { order(weight: 'asc') },
    dependent: :destroy
  has_one :main_product_image, -> { order(weight: 'asc') },
    class_name: :ProductImage

  scope :ascend, -> { order(weight: "asc") }
  scope :select_index_show, -> { where(index_show: true) }
  scope :ascend_index_weight, -> { order(index_weight: 'asc') }

  # 由微信端新增产品
  def self.create_form_wechat!(params)
    product = self.new title: params[:title],  sub_title: params[:sub_title], category_id: params[:category_id], description: params[:description], weight: params[:weight], price: params[:price], index_show: params[:index_show], is_hide: params[:is_hide], in_stock: params[:in_stock]
    if product.save
      return { status: "ok", id: product.id }
    else
      return { status: "failed", info: product.errors.messages.values.flatten }
    end
  end

  # 根据微信传来的参数更新产品栏位。。。
  def self.update_form_wechat!(params)
    product = self.find(params[:id])
      product.title = params[:title] if params[:title].present?
      product.sub_title = params[:sub_title] if params[:sub_title].present?
      product.description = params[:description] if params[:description].present?
      product.video = params[:video] if params[:video].present?
      product.price = params[:price] if params[:price].present?
      product.in_stock = params[:in_stock] if params[:in_stock].present?
      product.index_show = params[:index_show] if params[:index_show].present?
      product.is_hide = params[:is_hide] if params[:is_hide].present?
      product.weight = params[:weight] if params[:weight].present?
    return product.save ? { status: "ok", id: product.id } : { status: "failed", info: product.errors.messages.values.flatten }
  end

  # 更改is_hide状态
  def change_is_hide_status!
    self.is_hide = !self.is_hide
    self.save
  end

  # 更新in_stock状态
  def change_in_stock_status!
    self.in_stock = !self.in_stock
    self.save
  end

  # 更新index_show状态
  def change_index_show_status!
    self.index_show = !self.index_show
    self.save
  end

  def main_image_thumb
    if self.product_images.present?
      self.product_images.order(weight: 'asc').shuffle.last.image.thumb.url
    end
  end
  def main_image_small
    if self.product_images.present?
      self.product_images.order(weight: 'asc').shuffle.last.image.small.url
    end
  end
  def main_image_medium
    if self.product_images.present?
      self.product_images.order(weight: 'asc').shuffle.last.image.medium.url
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :auth_admin_or_wechat_user
  protect_from_forgery except: [:alipay_notify, :create_form_wechat, :update_form_wechat, :update_product_image, :add_product_image]
  before_action :find_product, only: [:destroy, :change_is_hide_status, :change_in_stock_status, :change_index_show_status, :change_is_hide_status, :delete_form_wechat]
  # 首页
  def index
    @q = Product.ransack(params[:q])
    @products = @q.result.includes(:category).paginate(:page => params[:page], :per_page => 25)
    respond_to do |format|
      format.html
      format.json{
        render :json => { products: @products.map{|p| { id: p.id, title: p.title, sub_title: p.sub_title, price: p.price, image: p.main_image_thumb}}, paginate: { current_page: @products.current_page, previous_page: @products.previous_page, next_page: @products.next_page, total_page: @products.total_pages} }
      }
    end
  end

  # 新增页面
  def new
    @product = Product.new
    @category_roots = Category.roots
  end

  # 新增产品
  def create
    @product = Product.new(product_params)
    if @product.save
      params[:product][:images].each do |img|
        @product.product_images << ProductImage.new(image: img)
      end
      redirect_to products_path, notice: "create success!新增成功~"
    else
      @category_roots = Category.roots
      flash[:warning] = @product.errors.messages.values.flatten.join("&")
      render :new
    end
  end

  def update
    @product = Product.new(product_params)
    if @product.save
      params[:product][:images].each do |img|
        @product.product_images << ProductImage.new(image: img)
      end
      redirect_to products_path, notice: "create success!新增成功~"
    else
      @category_roots = Category.roots
      flash[:warning] = @product.errors.messages.values.flatten.join("&")
      render :new
    end
  end

  # 微信端新增产品
  def create_form_wechat
    render json: Product.create_form_wechat!(params)
  end

  # 微信端更新产品数据
  def update_form_wechat
    render json: Product.update_form_wechat!(params)
  end

  # 微信端新增产品图片
  def add_product_image
    find_product
    @product.product_images.create image: params[:image]
    render :json => { status: "ok", id: params[:id]}
  end

  def show
    p = Product.find(params[:id])
    respond_to do |format|
      format.html
      format.json{
        random_product = Product.includes(:product_images).order("RANDOM()").limit(16)
        render :json => {product: {id: p.id, title: p.title, sub_title: p.sub_title, price: p.price, description: p.description, video: p.video.url, images: render_product_all_images(p) }, random_product: random_product.map{|p| { id: p.id, image: p.main_image_thumb, title: p.title, sub_title: p.sub_title, price: p.price}}, product_main_img: p.main_image_small}
      }
    end
  end

  def destroy
    if @product.destroy
      redirect_to :back, alert: "已删除！"
    else
      redirect_to :back, alert: "删除失败，请联系管理员！"
    end
  end

  # 小程序端编辑产品时获取产品详情
  def get_product_detail
    p = Product.find(params[:id])
    render :json => {id: p.id, title: p.title, sub_title: p.sub_title, description: p.description, price: p.price, video: p.video, weight: p.weight, index_show: p.index_show, in_stock: p.in_stock, is_hide: p.is_hide, image: p.product_images.order(weight: 'asc').map{|i| i.image.url}, category_id: p.category_id, category_title: p.category.title}
  end

  def change_is_hide_status
    @product.change_is_hide_status!
    redirect_to :back, notice: "更新成功！"
  end

   def change_in_stock_status
     @product.change_in_stock_status!
     redirect_to :back, notice: "更新成功！"
   end

   def change_index_show_status
     @product.change_index_show_status!
     redirect_to :back, notice: "更新成功！"
   end

  #  从小程序端删除产品
   def delete_form_wechat
     title = @product.title
     if @product.destroy
       render json: {status: "ok", info: "【#{title}】已删除~！"}
     end
   end

  private
  def product_params
    params.require(:product).permit(:title, :sub_title, :description, :video, :in_sale, :index_show, :weight, :price, :is_hide, :category_id)
  end

  def find_product
    @product = Product.find(params[:id])
  end

  def render_product_all_images(product)
    if product.product_images.present?
      product.product_images.order(weight: "asc").map{|i| i.image.medium.url}
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<legend class="text-center">产品管理<i class="fa fa-cogs" aria-hidden="true"></i></legend>
  <%= link_to "新增产品", new_product_path, class: "btn btn-info pull-right" %>
  <%= search_form_for @q, :url => products_path do |f| %>

    <p><%= f.search_field :title_or_sub_title_cont, :placeholder => "搜索商品", :class => "form-control" %></p>
    <%= f.submit "搜索", class: "btn btn-danger btn-block" %>
  <% end %>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>所属分类</th>
      <th>名称</th>
      <th>副标题</th>
      <th>详情</th>
      <th>价格</th>
      <th>视频</th>
      <th>是否有货</th>
      <th>首页展示？</th>
      <th>上架状态</th>
      <th>操作</th>
      <th>权重</th>
      <th>多图</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |p| %>
      <tr>
        <td><span class="label label-success label-sm"><%= p.category.title %></span></td>
        <td><%= p.title %></td>
        <td><%= p.sub_title %></td>
        <td><div style="width: 300px"><%= p.description %></div></td>
        <td><%= p.price %></td>
        <td width=400>
          <div style="width: 300px;" class="embed-responsive embed-responsive-4by3">
            <video controls class="embed-responsive-item" src="<%= p.video.url %>"></video>
          </div>
        </td>
        <td>
          <%= render_hide_status(p.in_stock == false) %>
          <%= link_to "更改状态", change_in_stock_status_product_path(p), method: :post, class: "btn btn-xs btn-primary" %>
        </td>
        <td>
          <%= render_hide_status(p.index_show == false) %>
          <%= link_to "更改状态", change_index_show_status_product_path(p), method: :post, class: "btn btn-xs btn-primary" %>
        </td>
        <td>
          <%= render_hide_status(p.is_hide) %>
          <%= link_to "更改状态", change_is_hide_status_product_path(p), method: :post, class: "btn btn-xs btn-primary" %>
        </td>
        <td><%= link_to "删除", product_path(p), method: :delete, "data-confirm": "确定吗？", class: "btn btn-sm btn-danger" %></td>
        <td><%= p.weight %></td>
        <td width=300>
           <div class="image-group">
             <% p.product_images.each do |img| %>
               <% if img.image.present? %>
                 <div class="image-item">
                   <%= image_tag(img.image.small.url, class: "thumbnail img-responsive") %>
                 </div>
               <% end %>
             <% end %>
           </div>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

<div class="text-center">
  <%= will_paginate @products %>
</div>

app/views/products/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <legend class="text-center" >新增产品</legend>

      <div class="dropdown">
       <%= label :category_id, "所属分类：" %><a id="dLabel" role="button" data-toggle="dropdown" class="btn btn-white" data-target="#" href="javascript:;"><span id="select-title">选择分类</span> <span class="caret"></span></a>
        <%= link_to "新增分类", new_category_path, class: "btn btn-xs btn-info pull-right" %>
        <ul class="dropdown-menu multi-level" role="menu" aria-labelledby="dropdownMenu">
          <% @category_roots.each do |root| %>
            <% if root.children? %>
                <li class="dropdown-submenu">
                  <a href="javascript:;" data-index="<%= root.id %>" data-title="<%= root.title %>"><%= root.title %></a>
                    <% root.children.each do |c| %>
                      <ul class="dropdown-menu">
                          <li><a data-index="<%= c.id %>" href="javascript:;" data-title="<%= c.title %>"><%= c.title %></a></li>
                      </ul>
                    <% end %>
                </li>
            <% else %>
              <li><a href="javascript:;" data-index="<%= root.id %>" data-title="<%= root.title %>"><%= root.title %></a></li>
            <% end %>
          <% end %>
        </ul>
      </div>

      <%= simple_form_for @product do |f| %>
        <%= f.input :title, label: "名称"%>
        <%= f.input :sub_title, label: "副标题" %>
        <%= f.input :description, label: "简介"%>
        <%= f.input :price, label: "价格" %>
        <%= f.label :images, "产品展示图（支持多图上传）" %>
        <%= f.file_field :images, :multiple => true, :class => "form-control form-group" %>
        <%= f.input :video, label: "上传产品小视频" %>
        <!-- <%= f.input :in_stock %> -->
        <div class="form-group">
          <%= f.check_box :index_show %>
          <%= f.label :index_show, "是否在首页展示？" %>
          <span class="pull-right">
            <%= f.label :weight, "优先级别：" %>
            <%= f.number_field :weight, placeholder: "值越大，排名越靠前！"%>
          </span>
        </div>

        <!-- <%= f.input :is_hide %> -->
        <input type="hidden" name="product[category_id]" id="category_id" value="" />
        <%= f.submit "提交", class: "btn btn-success btn-block" %>
      <% end %>
    </div>
  </div>
</div>


<script>
$('.dropdown li a').click(function(){

	console.log(this);
	title = $(this).attr("data-title");
	id = $(this).attr("data-index");
	$("#select-title").text(title);
	$("#category_id").val(id);
})

</script>