config/routes.rb
Rails.application.routes.draw do
  # 登入用：
  resources :sessions do
    collection do
      post :wechat_login
      post :admin_required
    end
  end

  root "welcome#home"
  resources :users
  delete '/logout' => 'sessions#destroy', as: :logout

  get "welcome" => "welcome#index"

  get '/admin/recent_login_log' => "admin/recent_login_log"
  get '/admin/get_user_login_log' => "admin/get_user_login_log"
  post "/kexue/update_ss_item" => "kexue/update_ss_item"
  get 'kexue/get_qr' => "kexue/get_qr"
  get 'kexue/show_qr' => "kexue/show_qr"
  get "kexue/show_wingy_qr" => "kexue/show_wingy_qr"
  get "server_data" => 'application#server_data'

  resources :categories do
    collection do
      get :for_wechat_product_new_picker
      get :for_wechat_category_new_picker
      post :create_form_api
    end
    member do
      post :update_column
      post :update_form_api
      get :get_category_detail
      post :change_index_show_status
      post :delete_category
    end
  end
  resources :products do
    collection do
      post :create_form_wechat
    end
    member do
      post :update_form_wechat
      post :add_product_image
      get :get_product_detail
      post :change_is_hide_status
      post :change_in_stock_status
      post :change_index_show_status
      post :delete_form_wechat
    end
  end
  resources :homeset do
    member do
      post :update_column
      post :update_column_homeset
      post :change_is_hide_status
    end
    collection do
      # 获取小程序首页的图片，标题等配置
      get :get_wechat_homeset
    end
  end
  resources :collects do
    collection do
      post :create_collect
      delete :remove_clooect
      get :my_collects
    end
  end


  resources :ss_services do
    resources :ss_items do
      member do
        get :admin_show_qr
        post :change_send_status
        post :init_draw_time
      end
    end
  end


end

app/views/common/_flashes.html.erb
<% if flash.any? %>
<% user_facing_flashes.each do |key, value| %>
<div class="alert alert-dismissable alert-<%= flash_class(key) %>">
  <button class="close" data-dismiss="alert">×</button>
  <%= value %>
</div>
<% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
  <p class="text-center">Copyright ©2017 xian_huiyu
    <br>Design by activeliang

  </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to content_tag(:i, (request.host.include?('huiyu') ? '亮锅后台' : '程序测试用'), class: "fa fa-home"), '/', class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to content_tag(:i, '分类管理', class: "fa fa-cubes"), categories_path %></li>
        <li><%= link_to content_tag(:i, '产品管理', class: "fa fa-gift"), products_path %></li>
        <li><%= link_to content_tag(:i, '小程序首页设置', class: "fa fa-sliders"), homeset_index_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">

        <% if !current_user %>

      <!---  <li><%= link_to(content_tag(:i, '更多', class: 'fa fa-user-plus'), new_user_path) %> </li>

        <li><%= link_to(content_tag(:i, '登入', class: 'fa fa-sign-in'),new_session_path)%></li>
      ---->    
      <!---  不 需要登录功能了 --->

      <% else %>

        <li class="dropdown">

          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Hi!, <%= current_user.phone %>

            <b class="caret"></b>

          </a>

          <ul class="dropdown-menu">

             <li> <%= link_to(content_tag(:i, '登出', class: 'fa fa-sign-out'), logout_path, method: :delete) %> </li>

          </ul>

        </li>

        <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>